services:
  postgres:
    image: postgres:15-alpine
    container_name: electrical_postgres
    environment:
      POSTGRES_USER: electrical_user
      POSTGRES_PASSWORD: electrical_password
      POSTGRES_DB: electrical_appliances_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: electrical_adminer
    ports:
      - "8082:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
